/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vending_machine;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionEvent;

/**
 *
 * @author afar0308
 */
public abstract class App extends javax.swing.JFrame {

    public App() {
        initComponents();
        initMainmenu();
        setVisible(true);
        setResizable(false);

        cl = (CardLayout)AppPanel.getLayout();
    }
    
    private void initMainmenu() {
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarClicked(evt);
            }
        });
        bOk.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkClicked(evt);
            }
        });
        mLogin.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginClicked(evt);
            }
        });
        mMainmenu.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMainmenuClicked(evt);
            }
        });
    }
    
    public int getSelectedMesin() {
        return daftarMesin.getSelectedIndex();
    }
    
    public void ubahJudul(String s) {
        super.setTitle(s);
    }
    
    public void tambahPanel(Container panel, String nama) {
        AppPanel.add(panel, nama);
    }
    
    public Container getPanel() {
        return AppPanel;
    }
    
    public void ubahPanel(String panel, String judul_window, int wWidth, int wHeight) {
        cl.show(AppPanel, panel);
        ubahJudul(judul_window);
        
        Dimension d = new Dimension(wWidth, wHeight);
        setMinimumSize(d);
        setSize(d);
    }
    
    public abstract void bKeluarClicked(ActionEvent evt);
    public abstract void bOkClicked(ActionEvent evt);
    public abstract void mLoginClicked(ActionEvent evt);
    public abstract void mMainmenuClicked(ActionEvent evt);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppPanel = new javax.swing.JPanel();
        main_menu = new javax.swing.JPanel();
        lJudul = new javax.swing.JLabel();
        lPilihan = new javax.swing.JLabel();
        daftarMesin = new javax.swing.JComboBox<>();
        bKeluar = new javax.swing.JButton();
        bOk = new javax.swing.JButton();
        snack_icon = new javax.swing.JLabel();
        mMenubar = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        mMainmenu = new javax.swing.JMenuItem();
        mLogin = new javax.swing.JMenuItem();
        mKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));

        AppPanel.setMinimumSize(new java.awt.Dimension(640, 459));
        AppPanel.setPreferredSize(new java.awt.Dimension(640, 459));
        AppPanel.setLayout(new java.awt.CardLayout());

        main_menu.setPreferredSize(new java.awt.Dimension(600, 400));

        lJudul.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lJudul.setText("SIMULASI VENDING MACHINE");

        lPilihan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lPilihan.setText("Pilihan:");

        daftarMesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesin Snack", "Mesin Minuman" }));

        bKeluar.setText("Keluar");

        bOk.setText("Ok");

        snack_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snack_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vending_machine/images/snack.jpg"))); // NOI18N
        snack_icon.setText("jLabel4");
        snack_icon.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout main_menuLayout = new javax.swing.GroupLayout(main_menu);
        main_menu.setLayout(main_menuLayout);
        main_menuLayout.setHorizontalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(main_menuLayout.createSequentialGroup()
                        .addComponent(lPilihan)
                        .addGap(43, 43, 43)
                        .addComponent(daftarMesin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lJudul)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_menuLayout.createSequentialGroup()
                        .addComponent(bKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(snack_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(bOk)))
                .addGap(123, 123, 123))
        );
        main_menuLayout.setVerticalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(main_menuLayout.createSequentialGroup()
                        .addComponent(lJudul)
                        .addGap(60, 60, 60)
                        .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPilihan)
                            .addComponent(daftarMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(snack_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bKeluar)))
                    .addComponent(bOk))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        AppPanel.add(main_menu, "card2");

        mMenu.setText("Menu");

        mMainmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mMainmenu.setText("Main Menu");
        mMenu.add(mMainmenu);

        mLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mLogin.setText("Login Admin");
        mMenu.add(mLogin);

        mKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mKeluar.setText("Keluar");
        mKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKeluarActionPerformed(evt);
            }
        });
        mMenu.add(mKeluar);

        mMenubar.add(mMenu);

        setJMenuBar(mMenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mKeluarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppPanel;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox<String> daftarMesin;
    private javax.swing.JLabel lJudul;
    private javax.swing.JLabel lPilihan;
    private javax.swing.JMenuItem mKeluar;
    private javax.swing.JMenuItem mLogin;
    private javax.swing.JMenuItem mMainmenu;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuBar mMenubar;
    private javax.swing.JPanel main_menu;
    private javax.swing.JLabel snack_icon;
    // End of variables declaration//GEN-END:variables
    public CardLayout cl;
}
