/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vending_machine;

import javax.swing.ImageIcon;

/**
 *
 * @author afar0308
 */
public abstract class login_admin extends javax.swing.JPanel {

    /**
     * Creates new form login_admin
     */
    public login_admin() {
        initComponents();
        initLogin();
    }
    
    private void initLogin() {
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginClicked(evt);
            }
        });
        Batal.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBatalClicked(evt);
            }
        });
    }
    
    public abstract void bLoginClicked(java.awt.event.MouseEvent evt);
    public abstract void bBatalClicked(java.awt.event.MouseEvent evt);
    
    public String getUsername() {
        return jTextField1.getText();
    }
    
    public String getPassword() {
        return new String(jPasswordField1.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Login = new javax.swing.JLabel();
        Batal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setOpaque(false);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 300, 30));

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 300, 30));

        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
        });
        add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 393, 160, 45));

        Batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BatalMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BatalMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BatalMouseEntered(evt);
            }
        });
        add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 394, 160, 45));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vending_machine/images/login.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMousePressed
        ImageIcon A = new ImageIcon("images/Login click.png");
        Login.setIcon(A);
    }//GEN-LAST:event_LoginMousePressed

    public void emptyField() {
        jTextField1.setText("");
        jPasswordField1.setText("");
        jTextField1.requestFocus();
    }
    
    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource(""));
        Login.setIcon(A);
    }//GEN-LAST:event_LoginMouseExited

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("images/Login enter.png"));
        Login.setIcon(A);
    }//GEN-LAST:event_LoginMouseEntered

    private void BatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatalMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("images/Batal click.png"));
        Batal.setIcon(A);
    }//GEN-LAST:event_BatalMousePressed

    private void BatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatalMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource(""));
        Batal.setIcon(A);
    }//GEN-LAST:event_BatalMouseExited

    private void BatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatalMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("images/Batal enter.png"));
        Batal.setIcon(A);
    }//GEN-LAST:event_BatalMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Batal;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
